import { NextRequest, NextResponse } from "next/server";
import crypto from "node:crypto";
import { createServiceRoleClient } from "@/lib/supabase/service";
import { getAuthedClient } from "@/lib/xero/client";
import { fetchXeroInvoice } from "@/lib/xero/invoices";
import { autoTransitionJobStatusServer } from "@/lib/job-status-transitions.server";
import { sendDDRecurringInvoiceEmail } from "@/lib/emails/dd-recurring-invoice";
import { logDocumentActivity } from "@/lib/activity/log";
import { enqueueNotification } from "@/lib/notifications/enqueue";

/**
 * Xero webhook receiver.
 *
 * Xero pings this endpoint when subscribed events fire (we subscribe to
 * INVOICE updates in the Xero developer portal). Each request is signed with
 * an HMAC-SHA256 of the raw body using `XERO_WEBHOOK_KEY` as the secret —
 * we MUST verify before doing anything, otherwise anyone can post arbitrary
 * payloads at us.
 *
 * Handshake: Xero verifies a new webhook by sending a signed empty/test
 * payload. If the signature matches we return 200, otherwise 401. Both
 * responses must be empty body and complete in <5s or Xero marks the
 * webhook unhealthy and stops sending events.
 *
 * On INVOICE.UPDATE we refresh the local invoice row by re-fetching from
 * Xero, then fire `invoice_paid` if the refresh shows it just flipped to
 * paid. Webhooks for non-mapped invoices (no local row) are silently
 * ignored.
 */

interface XeroWebhookEvent {
  resourceUrl: string;
  resourceId: string;
  eventDateUtc: string;
  eventType: "CREATE" | "UPDATE" | string;
  eventCategory: "INVOICE" | string;
  tenantId: string;
  tenantType: string;
}

interface XeroWebhookPayload {
  events: XeroWebhookEvent[];
  firstEventSequence: number;
  lastEventSequence: number;
  entropy: string;
}

function timingSafeEq(a: string, b: string): boolean {
  const ab = Buffer.from(a);
  const bb = Buffer.from(b);
  if (ab.length !== bb.length) return false;
  return crypto.timingSafeEqual(ab, bb);
}

export async function POST(req: NextRequest) {
  const key = process.env.XERO_WEBHOOK_KEY;
  if (!key) {
    console.error("[xero-webhook] XERO_WEBHOOK_KEY not set; refusing.");
    return new NextResponse(null, { status: 500 });
  }

  // Read the raw body — signature is computed over it byte-for-byte.
  const raw = await req.text();
  const sig = req.headers.get("x-xero-signature") ?? "";
  const expected = crypto.createHmac("sha256", key).update(raw, "utf8").digest("base64");

  if (!timingSafeEq(sig, expected)) {
    // Unsigned / wrong key — could be Xero's "intent to receive" dry-run
    // testing the wrong key, or a malicious request. Either way, 401.
    return new NextResponse(null, { status: 401 });
  }

  // Parse only after signature passes.
  let payload: XeroWebhookPayload;
  try {
    payload = JSON.parse(raw);
  } catch {
    return new NextResponse(null, { status: 400 });
  }

  // Acknowledge fast — Xero requires <5s response. Process events inline
  // anyway because they're cheap (single-invoice refresh + maybe a status
  // transition); push to background queue if this ever gets heavy.
  const supabase = createServiceRoleClient();

  for (const event of payload.events ?? []) {
    if (event.eventCategory !== "INVOICE") continue;
    if (event.eventType !== "UPDATE" && event.eventType !== "CREATE") continue;

    try {
      await processInvoiceEvent(supabase, event);
    } catch (err) {
      // Don't fail the whole batch if one event errors — log and move on.
      console.error(`[xero-webhook] event ${event.resourceId} failed:`, err);
    }
  }

  return new NextResponse(null, { status: 200 });
}

async function processInvoiceEvent(
  supabase: ReturnType<typeof createServiceRoleClient>,
  event: XeroWebhookEvent,
) {
  const xeroInvoiceId = event.resourceId;

  // Find the matching local invoice. If we don't have one, the invoice may
  // have been auto-generated by Xero from one of our RepeatingInvoice
  // templates — handle that case before silently ignoring.
  const { data: invoice } = await supabase
    .from("invoices")
    .select("id, status, job_id, invoice_type, xero_invoice_id")
    .eq("xero_invoice_id", xeroInvoiceId)
    .maybeSingle();

  // Refresh from Xero — gives us authoritative status, amountDue, paidOn date.
  // Pass the service-role supabase client so token refresh persistence works
  // past RLS (webhook is anonymous — no JWT/cookies).
  const { client, conn } = await getAuthedClient(supabase);
  const latest = await fetchXeroInvoice(client, conn.tenant_id, xeroInvoiceId);

  // If we have no local row, check whether this invoice was generated from
  // a RepeatingInvoice we own. If yes, ingest it + send the DD-aware email.
  if (!invoice) {
    if (latest.repeatingInvoiceID) {
      await ingestRecurringChildInvoice(supabase, xeroInvoiceId, latest);
    }
    return;
  }

  const status = latest.status.toLowerCase();
  const normalisedStatus =
    status === "paid" ? "paid"
    : status === "voided" ? "void"
    : status === "draft" ? "draft"
    : "authorised";

  const wasPaid = invoice.status === "paid";
  const nowPaid = normalisedStatus === "paid";

  await supabase
    .from("invoices")
    .update({
      amount_due: latest.amountDue,
      amount_paid: latest.amountPaid,
      status: normalisedStatus,
      paid_at: nowPaid
        ? (latest.fullyPaidOnDate
            ? new Date(latest.fullyPaidOnDate).toISOString()
            : new Date().toISOString())
        : null,
      xero_last_synced_at: new Date().toISOString(),
      xero_last_error: null,
    })
    .eq("id", invoice.id);

  // Log Xero state transitions on the invoice timeline. We only emit on the
  // edge — if the webhook fires repeatedly with the same status (Xero does
  // this when something orthogonal to status changes), we skip.
  if (invoice.status !== normalisedStatus) {
    await logDocumentActivity({
      supabase,
      documentType: "invoice",
      documentId: invoice.id,
      eventType: `invoice.${normalisedStatus === "paid" ? "paid"
        : normalisedStatus === "void" ? "voided"
        : normalisedStatus === "authorised" ? "authorised_in_xero"
        : "status_changed"}`,
      metadata: { from: invoice.status, to: normalisedStatus, amount_due: latest.amountDue, amount_paid: latest.amountPaid },
    });
  }

  // Only transition the job once, on the paid edge.
  if (!wasPaid && nowPaid && invoice.job_id) {
    // PP2 / final-payment path uses the existing `payment_received` rule
    // (Invoice Sent → Complete). PP1 / full path uses the new `invoice_paid`
    // rule (Awaiting Invoice Payment → Pending Schedule).
    const action = invoice.invoice_type === "progress_pp2" ? "payment_received" : "invoice_paid";
    try {
      await autoTransitionJobStatusServer(invoice.job_id, action, supabase);
    } catch (err) {
      console.error(`[xero-webhook] auto-transition failed for job ${invoice.job_id}:`, err);
    }
  }

  // Notify finance + the quote owner on the paid edge.
  if (!wasPaid && nowPaid) {
    await enqueueNotification({
      supabase,
      typeCode: "invoice.paid",
      refType: "invoice",
      refId: invoice.id,
      audience: { allActive: true },
      title: `Invoice paid · $${Number(latest.total).toFixed(2)}`,
      body: latest.invoiceNumber ? `${latest.invoiceNumber} marked paid in Xero.` : "Invoice marked paid in Xero.",
      href: `/invoices/${invoice.id}`,
    });
  }
}

/**
 * Xero auto-generated this invoice from one of our RepeatingInvoice
 * templates. Match the template back to the recurring plan, insert a local
 * `invoices` row of type `recurring`, then email the customer with the
 * DD-aware "no action needed" copy.
 *
 * Idempotent: if the invoice was already ingested (subsequent UPDATE
 * webhooks for the same Xero invoice ID), the dedupe at the top of
 * processInvoiceEvent will catch it and route through the normal path.
 */
async function ingestRecurringChildInvoice(
  supabase: ReturnType<typeof createServiceRoleClient>,
  xeroInvoiceId: string,
  latest: Awaited<ReturnType<typeof fetchXeroInvoice>>,
) {
  if (!latest.repeatingInvoiceID) return;

  // Find the plan owning this RepeatingInvoice template. Note we check both
  // the primary RI id and the secondary one (yearly plans split into two
  // templates — primary stored on plan, secondary mentioned in notes).
  const { data: plan } = await supabase
    .from("recurring_plans")
    .select(`
      id, customer_id, site_id, status, alias_email,
      customers(id, name, customer_contacts(name, email, is_primary)),
      customer_sites(name),
      recurring_plan_items(service_name, quantity)
    `)
    .eq("xero_repeating_invoice_id", latest.repeatingInvoiceID)
    .maybeSingle();

  if (!plan) {
    console.log(`[xero-webhook] no plan owns RI ${latest.repeatingInvoiceID}; ignoring`);
    return;
  }

  const status = latest.status.toLowerCase();
  const normalisedStatus =
    status === "paid" ? "paid"
    : status === "voided" ? "void"
    : status === "draft" ? "draft"
    : "authorised";

  // Insert the local row first so duplicate webhooks dedupe cleanly.
  const { data: inserted, error: insertErr } = await supabase
    .from("invoices")
    .insert({
      invoice_type: "recurring",
      customer_id: plan.customer_id,
      description: `Recurring billing — ${
        Array.isArray(plan.customer_sites) ? plan.customer_sites[0]?.name : (plan.customer_sites as { name?: string } | null)?.name
      }`,
      line_items: [],
      subtotal: 0,
      gst: 0,
      total: latest.total,
      amount_due: latest.amountDue,
      amount_paid: latest.amountPaid,
      status: normalisedStatus,
      xero_invoice_id: xeroInvoiceId,
      xero_invoice_number: latest.invoiceNumber,
      xero_last_synced_at: new Date().toISOString(),
      issued_at: new Date().toISOString(),
      due_date: latest.dueDate,
      auto_created: true,
    })
    .select("id")
    .single();

  if (insertErr || !inserted) {
    console.error(`[xero-webhook] failed to insert recurring child:`, insertErr);
    return;
  }

  await logDocumentActivity({
    supabase,
    documentType: "invoice",
    documentId: inserted.id,
    eventType: "invoice.created",
    metadata: { source: "recurring", xero_invoice_number: latest.invoiceNumber, recurring_plan_id: plan.id },
  });

  // Send the DD-aware email. Best-effort — log but don't throw if Resend fails.
  try {
    const customer = Array.isArray(plan.customers) ? plan.customers[0] : plan.customers;
    const site = Array.isArray(plan.customer_sites) ? plan.customer_sites[0] : plan.customer_sites;
    const primary = customer?.customer_contacts?.find((c: { is_primary: boolean }) => c.is_primary)
      ?? customer?.customer_contacts?.[0];
    if (!primary?.email) {
      console.warn(`[xero-webhook] plan ${plan.id} customer has no primary email; skipping recurring email`);
      return;
    }

    const items = plan.recurring_plan_items ?? [];
    const serviceSummary = items.length === 0
      ? "Recurring services"
      : items.map((it: { service_name: string; quantity: number }) => it.quantity > 1 ? `${it.service_name} × ${it.quantity}` : it.service_name).join(", ");

    await sendDDRecurringInvoiceEmail({
      to: primary.email,
      customerName: primary.name ?? customer?.name ?? "there",
      siteLabel: site?.name ?? customer?.name ?? "your account",
      invoiceNumber: latest.invoiceNumber,
      total: latest.total,
      debitDate: latest.dueDate,
      xeroOnlineUrl: null, // RI children don't have OnlineInvoiceUrl unless explicitly fetched separately
      serviceSummary,
      invoiceId: inserted.id,
    });
  } catch (err) {
    console.error(`[xero-webhook] DD recurring email failed for plan ${plan.id}:`, err);
  }
}
